const SUPABASE_URL = "https://vdrmoofaqnqhdpxbljif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_ntiUF2cHpgcKpWthmrzO-A_gANC6TbG";

const supabase = window.supabase.createClient(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const TYPES={music:["♫","MUSIC"],letter:["✉","LETTER"],poetry:["❝","POETRY"],fragment:["☁","RANDOM TEXT"],image:["▧","IMAGE"],video:["▶","VIDEO"],place:["⌖","PLACE"]};
const normalizeEntry=x=>{let e={...x};if(e.type==="sound")e.type="video";if(e.type==="object"){e.type="fragment";e.body=[e.title,e.note].filter(Boolean).join("\n");delete e.title;delete e.note}e.id=String(e.id||crypto.randomUUID());return e};
let entries=JSON.parse(localStorage.getItem("entryArchiveV4")||"[]").map(normalizeEntry),filter="all",selectedType="",editingId=null,dateFilter="";
entries=entries.map(normalizeEntry);
const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const dateText=d=>new Date(d+"T12:00:00").toLocaleDateString("en-GB").replaceAll("/",".");
const save=()=>localStorage.setItem("entryArchiveV4",JSON.stringify(entries));
$("#today").textContent=new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date()).replaceAll("/",".");
function embed(u){const m=String(u||"").match(/open\.spotify\.com\/(?:intl-[^/]+\/)?track\/([A-Za-z0-9]+)/);return m?`https://open.spotify.com/embed/track/${m[1]}?utm_source=generator`:""}
function card(e){let [s,l]=TYPES[e.type],c="";
if(e.type==="music"){let em=embed(e.spotify);c=`<div class="music-card"><div class="album">${e.cover?`<img src="${esc(e.cover)}" alt="">`:"♫"}</div><div class="music-info"><h2>${esc(e.title)}</h2><p>${esc(e.artist)}</p>${em?`<iframe class="spotify-frame" src="${em}" allow="autoplay;clipboard-write;encrypted-media;fullscreen;picture-in-picture"></iframe><div class="spotify-credit"><a href="${esc(e.spotify)}" target="_blank" rel="noopener">OPEN IN SPOTIFY ↗</a> · Spotify</div>`:""}</div></div>${e.note?`<p>${esc(e.note)}</p>`:""}`}
if(e.type==="letter")c=`<div class="paper"><h2>${esc(e.title)}</h2><p>${esc(e.body).replace(/\n/g,"<br>")}</p></div>`;
if(e.type==="poetry")c=`<div class="poem">${e.title?`<h2>${esc(e.title)}</h2>`:""}<p>${esc(e.body).replace(/\n/g,"<br>")}</p></div>`;
if(e.type==="fragment")c=`<p class="fragment">“${esc(e.body)}”</p>`;
if(e.type==="image")c=`<div class="image-entry"><img src="${esc(e.image)}" alt=""></div><p>${esc(e.title||"")}</p>`;
if(e.type==="video"){const yt=String(e.youtube||"").match(/(?:youtube\.com\/(?:watch\?v=|shorts\/|live\/)|youtu\.be\/)([A-Za-z0-9_-]{6,})/);const ytembed=yt?`https://www.youtube-nocookie.com/embed/${yt[1]}?rel=0`:"";const isFile=location.protocol==='file:';c=`<div class="paper"><h2>${esc(e.title)}</h2>${e.video?`<video class="video-player" controls src="${esc(e.video)}"></video>`:""}${ytembed&&!isFile?`<div class="video-wrap"><iframe src="${ytembed}" title="YouTube video" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>`:""}${e.youtube?(isFile?`<p class="hint">YouTube can't embed when ENTRY is opened directly as a file, so use the button below.</p>`:"")+`<p><a href="${esc(e.youtube)}" target="_blank" rel="noopener">WATCH ON YOUTUBE ↗</a></p>`:""}<p>${esc(e.note||"")}</p></div>`;}
if(e.type==="place")c=`<div class="place-card"><div class="map-placeholder">⌖<br>${esc(e.coordinates||"")}</div><div><p class="eyebrow">PLACE</p><h2>${esc(e.title)}</h2><p>${esc(e.note)}</p></div></div>`;
return `<article class="entry" data-id="${e.id}"><div class="entry-meta"><span>${s} ${l}</span><time>${dateText(e.date)}</time></div><div class="entry-actions"><button data-edit="${e.id}" type="button">EDIT</button><button data-delete="${e.id}" type="button">DELETE</button></div>${c}</article>`}
function render(){let a=entries.filter(e=>(filter==="all"||e.type===filter)&&(!dateFilter||e.date===dateFilter));$("#entries").innerHTML=a.length?a.map(card).join(""):`<div class="empty"><span>∅</span><h2>Nothing here yet.</h2><p>This part of the archive is waiting for something to happen.</p></div>`;$("#count").textContent=String(entries.length).padStart(3,"0")}
render();
async function syncApproved(){if(location.protocol==='file:')return;try{const r=await fetch('/api/approved');if(!r.ok)return;const d=await r.json();const localIds=new Set(entries.map(x=>x.id));const approved=(d.entries||[]).filter(x=>!localIds.has(x.id));if(approved.length){entries=[...entries,...approved];render()}}catch(e){}}
syncApproved();
$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});
$("#newEntry").onclick=()=>{editingId=null;$("#modal").classList.remove("hidden");$("#entryForm").classList.add("hidden")};
$("#closeModal").onclick=()=>$("#modal").classList.add("hidden");
function fld(n,l,t="text",v="",r=false){return `<div class="field"><label>${l}</label>${t==="textarea"?`<textarea name="${n}" ${r?"required":""}>${esc(v)}</textarea>`:`<input name="${n}" type="${t}" value="${esc(v)}" ${r?"required":""}>`}</div>`}
function selectType(t,old={}){selectedType=t;$$('.type-picker button').forEach(b=>b.classList.toggle('selected',b.dataset.type===t));let h=fld('date','DATE','date',old.date||new Date().toISOString().slice(0,10),true);
if(t==='music')h+=fld('title','SONG TITLE','text',old.title,true)+fld('artist','ARTIST','text',old.artist,true)+fld('spotify','SPOTIFY LINK','url',old.spotify)+`<input type="hidden" name="cover" value="${esc(old.cover||"")}"><div id="coverStatus" class="hint">${old.cover?'Album image loaded.':'Paste a Spotify track link to load the album image automatically.'}</div>`+fld('note','WHY THIS SONG?','textarea',old.note);
if(t==='letter')h+=fld('title','TO / TITLE','text',old.title,true)+fld('body','LETTER','textarea',old.body,true);
if(t==='poetry')h+=fld('title','TITLE','text',old.title)+fld('body','POEM','textarea',old.body,true);
if(t==='fragment')h+=fld('body','RANDOM TEXT','textarea',old.body,true);
if(t==='image')h+=fld('title','CAPTION','text',old.title)+`<div class="field"><label>IMAGE FILE</label><input name="imageFile" type="file" accept="image/*"><div class="hint">Choose an image from your computer.</div></div>`+`<input type="hidden" name="image" value="${esc(old.image||'')}">`;
if(t==='video')h+=fld('title','VIDEO','text',old.title,true)+`<div class="field"><label>VIDEO FILE</label><input name="videoFile" type="file" accept="video/*"><div class="hint">Choose a video file from your computer.</div></div>`+fld('youtube','YOUTUBE URL','url',old.youtube)+`<div class="hint">Use either a video file or a YouTube link.</div>`+`<input type="hidden" name="video" value="${esc(old.video||'')}">`+fld('note','DESCRIPTION','textarea',old.note);
if(t==='place')h+=fld('title','PLACE','text',old.title,true)+fld('coordinates','COORDINATES','text',old.coordinates)+fld('note','MEMORY','textarea',old.note,true);
$('#dynamicFields').innerHTML=h;$('#entryForm').classList.remove('hidden');if(t==='music'){const u=$('#dynamicFields [name=spotify]');u.oninput=()=>loadSpotifyMeta(u.value);u.onblur=()=>loadSpotifyMeta(u.value);if(old.spotify&&!old.cover)loadSpotifyMeta(old.spotify)}}
$$('.type-picker button').forEach(b=>b.onclick=()=>selectType(b.dataset.type));
async function loadSpotifyMeta(url){const m=String(url||'').match(/^https?:\/\/(?:open\.)?spotify\.com\/(?:intl-[^/]+\/)?track\/([A-Za-z0-9]+)/);if(!m)return;const status=$('#coverStatus');if(status)status.textContent='Loading album image…';try{const r=await fetch('https://open.spotify.com/oembed?url='+encodeURIComponent(url));if(!r.ok)throw new Error();const d=await r.json();const cover=$('#dynamicFields [name=cover]');const title=$('#dynamicFields [name=title]');const artist=$('#dynamicFields [name=artist]');if(cover)cover.value=d.thumbnail_url||'';if(title&&!title.value)title.value=d.title||'';if(artist&&!artist.value)artist.value=d.author_name||'';if(status)status.textContent=d.thumbnail_url?'Album image loaded automatically.':'Song found, but no album image was returned.'}catch(e){if(status)status.textContent='Could not load Spotify info yet.'}}
$('#entryForm').onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));d.type=selectedType;if(selectedType==='image'){const file=$('#dynamicFields [name=imageFile]')?.files?.[0];if(file){if(file.size>5*1024*1024){alert('That image is too large. Please choose an image under 5 MB.');return}d.image=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}delete d.imageFile}if(selectedType==='video'){const file=$('#dynamicFields [name=videoFile]')?.files?.[0];if(file){if(file.size>12*1024*1024){alert('That video is too large. Please choose a video under 12 MB.');return}d.video=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}delete d.videoFile}d=normalizeEntry(d);if(editingId){d.id=String(editingId);entries=entries.map(x=>String(x.id)===String(editingId)?d:x)}else{entries.push(d)}save();render();$('#modal').classList.add('hidden');editingId=null};
$('#entries').onclick=e=>{let del=e.target.dataset.delete,ed=e.target.dataset.edit;if(del&&confirm('Delete this entry?')){entries=entries.filter(x=>String(x.id)!==String(del));save();render()}if(ed){let x=entries.find(x=>x.id===ed);if(x){editingId=x.id;$('#modal').classList.remove('hidden');selectType(x.type,x)}}};
$('#dateSearch').onchange=e=>{dateFilter=e.target.value;render()};
$('#clearDate').onclick=()=>{$('#dateSearch').value='';dateFilter='';render()};
$('#randomEntry').onclick=()=>{let a=[...document.querySelectorAll('.entry')];if(a.length)a[Math.floor(Math.random()*a.length)].scrollIntoView({behavior:'smooth',block:'center'})};
$('#exportBtn').onclick=()=>{const backup={app:'ENTRY',version:2,exportedAt:new Date().toISOString(),entries:entries.map(normalizeEntry)};const blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='entry-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('#importBtn').onclick=()=>$('#backupFile').click();
$('#backupFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data?.app!=='ENTRY'||!Array.isArray(data.entries))throw new Error('Invalid backup');if(!confirm(`Load ${data.entries.length} entries from this backup? This will replace the entries currently in ENTRY.`))return;entries=data.entries.map(normalizeEntry);save();render();alert('Backup loaded successfully.')}catch(err){alert('That does not look like a valid ENTRY backup.')}finally{e.target.value=''}};


// FRIENDS / SHARED ARCHIVE
let friendType='', friendEditingData={};
function friendFld(n,l,t='text',v='',r=false){return fld(n,l,t,v,r)}
function selectFriendType(t){friendType=t;$$('#friendTypePicker button').forEach(b=>b.classList.toggle('selected',b.dataset.type===t));let h=friendFld('name','YOUR NAME (OPTIONAL)')+friendFld('date','DATE','date',new Date().toISOString().slice(0,10),true);
if(t==='music')h+=friendFld('title','SONG TITLE','text','',true)+friendFld('artist','ARTIST','text','',true)+friendFld('spotify','SPOTIFY LINK','url','',true);
if(t==='letter')h+=friendFld('title','TO / TITLE','text','',true)+friendFld('body','LETTER','textarea','',true);
if(t==='poetry')h+=friendFld('title','TITLE')+friendFld('body','POEM','textarea','',true);
if(t==='fragment')h+=friendFld('body','RANDOM TEXT','textarea','',true);
if(t==='image')h+=`<div class="field"><label>IMAGE FILE</label><input name="imageFile" type="file" accept="image/*" required><div class="hint">Choose an image from your computer.</div></div>`+friendFld('title','CAPTION');
if(t==='video')h+=friendFld('title','VIDEO','text','',true)+friendFld('youtube','YOUTUBE URL','url')+`<div class="field"><label>VIDEO FILE</label><input name="videoFile" type="file" accept="video/*"><div class="hint">Use either a YouTube link or a video file.</div></div>`;
if(t==='place')h+=friendFld('title','PLACE','text','',true)+friendFld('coordinates','COORDINATES')+friendFld('note','MEMORY','textarea','',true);
$('#friendFields').innerHTML=h;$('#friendForm').classList.remove('hidden');}
async function fileData(input,max){const f=input?.files?.[0];if(!f)return '';if(f.size>max)throw new Error('file-too-large');return await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)})}
$('#friendsBtn').onclick=()=>{$('#friendModal').classList.remove('hidden');$('#friendForm').classList.add('hidden')};
$('#closeFriendModal').onclick=()=>$('#friendModal').classList.add('hidden');
$$('#friendTypePicker button').forEach(b=>b.onclick=()=>selectFriendType(b.dataset.type));
$('#friendForm').onsubmit=async e=>{e.preventDefault();if(location.protocol==='file:'){alert('Friends submissions need ENTRY to be hosted online first.');return}let d=Object.fromEntries(new FormData(e.target));d.type=friendType;try{if(friendType==='image'){d.image=await fileData(e.target.imageFile,5*1024*1024);delete d.imageFile}if(friendType==='video'){d.video=await fileData(e.target.videoFile,12*1024*1024);delete d.videoFile}const r=await fetch('/api/submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});if(!r.ok)throw new Error();alert('Sent ♡ It is waiting for approval.');e.target.reset();$('#friendModal').classList.add('hidden')}catch(err){alert(err.message==='file-too-large'?'That file is too large.':'Could not send the entry yet.')}};
async function openInbox(){if(location.protocol==='file:'){alert('The inbox is available on the hosted ENTRY site.');return}let key=sessionStorage.getItem('entryAdminKey')||prompt('ADMIN KEY');if(!key)return;let r=await fetch('/api/inbox',{headers:{'x-admin-key':key}});if(r.status===401){sessionStorage.removeItem('entryAdminKey');alert('Wrong admin key.');return}sessionStorage.setItem('entryAdminKey',key);let d=await r.json();$('#inboxContent').innerHTML=(d.submissions||[]).length?d.submissions.map(x=>`<div class="paper" style="margin-bottom:16px"><p class="eyebrow">${esc(x.type)} · ${esc(x.date||'')}</p><h2>${esc(x.title||x.name||'Untitled')}</h2><p>${esc(x.body||x.note||x.artist||x.youtube||'')}</p><p class="hint">FROM: ${esc(x.name||'anonymous')} · STATUS: ${esc(x.status)}</p>${x.status==='pending'?`<button class="save-btn" data-approve="${x.id}">KEEP</button> <button class="plain-btn" data-reject="${x.id}">REJECT</button>`:''}</div>`).join(''):'<p class="hint">Nothing waiting.</p>';$('#inboxModal').classList.remove('hidden')}
$('#inboxBtn').onclick=openInbox;$('#closeInboxModal').onclick=()=>$('#inboxModal').classList.add('hidden');
$('#inboxContent').onclick=async e=>{const id=e.target.dataset.approve||e.target.dataset.reject;if(!id)return;const action=e.target.dataset.approve?'approve':'reject',key=sessionStorage.getItem('entryAdminKey');const r=await fetch('/api/submissions/'+id,{method:'POST',headers:{'Content-Type':'application/json','x-admin-key':key},body:JSON.stringify({action})});if(r.ok){await syncApproved();openInbox()}};
